// <auto-generated />
using BakeryShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BakeryShop.Data.Migrations
{
    [DbContext(typeof(BakeryShopContext))]
    [Migration("20190828174502_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BakeryShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImageName")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Carrot Cake Any Description",
                            ImageName = "carrot_cake.jpg",
                            Name = "Carrot Cake",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lemo Tart Any Description",
                            ImageName = "lemon_tart.jpg",
                            Name = "Lemo Tart",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cup Cakes Any Description",
                            ImageName = "carrot_cake.jpg",
                            Name = "Cup Cakes",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            Description = "ITShare Carrot Cake Any Description",
                            ImageName = "cupcakes.jpg",
                            Name = "ITShare Carrot Cake",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bread Any Description",
                            ImageName = "bread.jpg",
                            Name = "Bread",
                            Price = 0m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chocolate Cake Any Description",
                            ImageName = "chocolate_cake.jpg",
                            Name = "Chocolate Cake",
                            Price = 0m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pear Tart Any Description",
                            ImageName = "pear_tart.jpg",
                            Name = "Pear Tart",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
